In [79]:
#Create and display one dimensional series

import pandas as pd

data = pd.Series([10,20,30,40,50])
print("Pandas Series:")

print(data)

Pandas Series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

In [80]:
#convert series to python list

s = pd.Series([10,20,30,40,50])
print(s)
s_list = s.tolist()
s_list

0    10
1    20
2    30
3    40
4    50
dtype: int64

[10, 20, 30, 40, 50]

In [81]:
#ARithmatic operation on pandas series

series1 = pd.Series([2, 4, 6, 8, 10])
series2 = pd.Series([1, 3, 5, 7, 9])

print("Addition\n",[ series1 + series2])
print("Addition\n",[ series1 - series2])
print("Addition\n",[ series1 * series2])
print("Addition\n",[ series1 / series2])

Addition
 [0     3
1     7
2    11
3    15
4    19
dtype: int64]
Addition
 [0    1
1    1
2    1
3    1
4    1
dtype: int64]
Addition
 [0     2
1    12
2    30
3    56
4    90
dtype: int64]
Addition
 [0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64]

In [82]:
#Element-wise  Power of Array Values

# Creating the base Series
ds1 = pd.Series([0, 1, 2, 3, 4, 5, 6])

# Creating the exponent Series (all 3s to match your expected output)
ds2 = pd.Series([3, 3, 3, 3, 3, 3, 3])

result = ds1.pow(ds2)

print(ds1)
print(ds2)
print(result)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
dtype: int64
0    3
1    3
2    3
3    3
4    3
5    3
6    3
dtype: int64
0      0
1      1
2      8
3     27
4     64
5    125
6    216
dtype: int64

In [83]:

exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index=labels)
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [84]:
# Get first three rows of given data frame 

exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index=labels)
df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [85]:
df.head(3)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

In [86]:
#select two columns only
ans = (df[['name','score']])
ans

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

In [87]:
#select from the specfic row and columns 

print(df.iloc[[1,3,5,6],[0,1]])

      name  score
b     Dima    9.0
d    James    NaN
f  Michael   20.0
g  Matthew   14.5

In [88]:
#print rows where attempt > 2
print(df)

ans = (df[df['attempts'] > 2])
ans

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

In [89]:
#Count number of rows and columns 
# df.info()

rows = len(df.index)
cols = len(df.columns)
print(rows)
print(cols)

10
4

In [90]:
df.isna()
#print where score is null
print(df[df['score'].isnull()])

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

In [91]:
df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [92]:
ans = (df[(df['attempts'] < 2) & (df['score'] > 15)])
ans

    name  score  attempts qualify
j  Jonas   19.0         1     yes

In [93]:
df.loc['d','score'] = 11.5

df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [94]:
sum = (df['attempts']).sum()
sum

np.int64(19)

In [95]:
mean = (df['score']).mean()
mean

np.float64(13.333333333333334)

In [96]:
df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [97]:
df.loc['k'] = ['Gurav' , 'Ahira' , 12 , 10 ]
df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
k      Gurav  Ahira        12      10

In [98]:
df = df.drop('k')
print(df)

        name score  attempts qualify
a  Anastasia  12.5         1     yes
b       Dima   9.0         3      no
c  Katherine  16.5         2     yes
d      James  11.5         3      no
e      Emily   9.0         2      no
f    Michael  20.0         3     yes
g    Matthew  14.5         1     yes
h      Laura   NaN         1      no
i      Kevin   8.0         2      no
j      Jonas  19.0         1     yes

In [99]:
sort = df.sort_values(by=['name' , 'score'], ascending= False)
sort

        name score  attempts qualify
f    Michael  20.0         3     yes
g    Matthew  14.5         1     yes
h      Laura   NaN         1      no
i      Kevin   8.0         2      no
c  Katherine  16.5         2     yes
j      Jonas  19.0         1     yes
d      James  11.5         3      no
e      Emily   9.0         2      no
b       Dima   9.0         3      no
a  Anastasia  12.5         1     yes

In [100]:
sort = df.sort_values(by = 'score', ascending= True)
sort

        name score  attempts qualify
i      Kevin   8.0         2      no
b       Dima   9.0         3      no
e      Emily   9.0         2      no
d      James  11.5         3      no
a  Anastasia  12.5         1     yes
g    Matthew  14.5         1     yes
c  Katherine  16.5         2     yes
j      Jonas  19.0         1     yes
f    Michael  20.0         3     yes
h      Laura   NaN         1      no

In [101]:
df['qualify'] = df['qualify'].map({'yes': True, 'no': False})
df

        name score  attempts  qualify
a  Anastasia  12.5         1     True
b       Dima   9.0         3    False
c  Katherine  16.5         2     True
d      James  11.5         3    False
e      Emily   9.0         2    False
f    Michael  20.0         3     True
g    Matthew  14.5         1     True
h      Laura   NaN         1    False
i      Kevin   8.0         2    False
j      Jonas  19.0         1     True

In [103]:
df.pop('attempts')
print(df)

        name score  qualify
a  Anastasia  12.5     True
b       Dima   9.0    False
c  Katherine  16.5     True
d      James  11.5    False
e      Emily   9.0    False
f    Michael  20.0     True
g    Matthew  14.5     True
h      Laura   NaN    False
i      Kevin   8.0    False
j      Jonas  19.0     True

In [104]:
# New column data
color = ['Red', 'Blue', 'Orange', 'Red', 'White', 'White', 'Blue', 'Green', 'Green', 'Red']

# Inserting the column
df['color'] = color

In [105]:
df

        name score  qualify   color
a  Anastasia  12.5     True     Red
b       Dima   9.0    False    Blue
c  Katherine  16.5     True  Orange
d      James  11.5    False     Red
e      Emily   9.0    False   White
f    Michael  20.0     True   White
g    Matthew  14.5     True    Blue
h      Laura   NaN    False   Green
i      Kevin   8.0    False   Green
j      Jonas  19.0     True     Red

In [106]:
print("Iterating over rows:")
for index, row in df.iterrows():
    print(f"Index: {index}, Name: {row['name']}, Score: {row['score']}")

Iterating over rows:
Index: a, Name: Anastasia, Score: 12.5
Index: b, Name: Dima, Score: 9.0
Index: c, Name: Katherine, Score: 16.5
Index: d, Name: James, Score: 11.5
Index: e, Name: Emily, Score: 9.0
Index: f, Name: Michael, Score: 20.0
Index: g, Name: Matthew, Score: 14.5
Index: h, Name: Laura, Score: nan
Index: i, Name: Kevin, Score: 8.0
Index: j, Name: Jonas, Score: 19.0

In [107]:
import pandas as pd
import numpy as np

exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1]
}
df = pd.DataFrame(exam_data)

# Get column headers
column_headers = list(df.columns)

print("Column Headers:")
print(column_headers)

Column Headers:
['name', 'score', 'attempts']